#!/usr/bin/env bash
# install
#
# Dotfiles Installer
# This script will run any custom installer.sh files that are present.
# It will then symlink any .symlink files into your user root.

export DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DOTFILES_ROOT/dotfiles.sh"

set -e

echo ''
echo '======================================================'
echo '             ✨  Dotfiles Installer ✨'
echo '======================================================'
echo ''

# Find any included installers and run them iteratively
find $DOTFILES_ROOT -name installer.sh -exec {} \;

# Setup symlinks for all dotfiles with a .symlink extention
setup_symlinks () {
  echo '==> Setting Dotfile Symlinks...'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    set_symlink "$src" "$dst"
  done
}
setup_symlinks

echo 'Installation complete!'
echo ''
