#!/usr/bin/env bash
#
# Dotfiles setup script
# Sets up the gitconfig and runs the dotfiles installer
#

export XDG_CONFIG_HOME="$HOME/.config"

cd "$(dirname "$0")/.."

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f $XDG_CONFIG_HOME/git/gitconfig.local.sylk ]
  then
    echo ''
    info '==> setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $XDG_CONFIG_HOME/git/gitconfig.local.sylk.example > $XDG_CONFIG_HOME/git/gitconfig.local.sylk

    success '> gitconfig'
  fi
}

install_dotfiles() {
  info '==> Running dotfiles installer...'

  if source $XDG_CONFIG_HOME/bin/dotfiles | exec dotfiles update | while read -r data; do info "$data"; done
  then
    success 'XDG dotfiles installed'
  else
    fail 'Error installing XDG dotfiles'
  fi
}

setup_gitconfig
install_dotfiles
