cask_args appdir: '/Applications'

tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'

# Programming
brew 'crystal'
brew 'elixir'
brew 'node'
brew 'python'
brew 'ruby'

# CLI
brew 'git'
brew 'git-crypt'
brew 'htop'
brew 'tmux'
brew 'vim'
brew 'yarn'

# Devops
brew 'awscli'
brew 'doctl'
brew 'kubectl'

# Applications
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'postman'
cask 'postico'
cask 'sequel-pro'
cask 'slack'
cask 'visual-studio-code'

## Fonts
cask 'font-menlo-for-powerline'
